# Generated by Django 5.2.5 on 2025-08-26 13:58

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "faculty"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "department",
                    models.CharField(default="Computer Application", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Faculty Profile",
                "verbose_name_plural": "Faculty Profiles",
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Student Group",
                "verbose_name_plural": "Student Groups",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Use your official Jain University email address.",
                max_length=254,
                unique=True,
                validators=[core.validators.CollegeEmailValidator()],
                verbose_name="college email address",
            ),
        ),
        migrations.CreateModel(
            name="HODProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "hod"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "department",
                    models.CharField(default="Computer Application", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "responsible_for_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select the student groups this HOD is responsible for.",
                        related_name="hods",
                        to="core.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "HOD Profile",
                "verbose_name_plural": "HOD Profiles",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Unique student identifier (e.g., Enrollment Number).",
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="core.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
    ]
