# Generated by Django 5.2.5 on 2025-08-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_facultyprofile_studentgroup_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
